language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update

install:
  # C++11
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" = "g++-4.8" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install libstdc++-4.8-dev; fi

  - sudo apt-get install cmake

  # SFML 2.2
  - sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev
       libxrandr-dev libfreetype6-dev libglew-dev libjpeg8-dev
       libsndfile1-dev libopenal-dev libudev-dev
  - wget http://www.sfml-dev.org/files/SFML-2.2-sources.zip
  - unzip SFML-2.2-sources.zip
  - cd SFML-2.2/
  - mkdir build && cd build/
  - cmake ..
  - make
  - sudo make install
  - cd ../../

  # Box2D 2.3.0
  - sudo apt-get install freeglut3-dev libxi-dev
  - wget https://box2d.googlecode.com/files/Box2D_v2.3.0.7z
  - sudo apt-get install p7zip p7zip-full
  - 7z x Box2D_v2.3.0.7z
  - cd Box2D_v2.3.0/Box2D/
  - mkdir build && cd build/
  - cmake -DBOX2D_INSTALL=ON -DBOX2D_BUILD_SHARED=ON ..
  - make
  - sudo make install
  - cd ../../../

  # EnetPlus
  - sudo apt-get install libenet1a libenet-dev
  - wget https://github.com/xairy/enet-plus/releases/download/v0.1-alpha/libenet-plus_0.1-1_amd64.deb
  - wget https://github.com/xairy/enet-plus/releases/download/v0.1-alpha/libenet-plus-dev_0.1-1_amd64.deb
  - sudo dpkg -i libenet-plus_0.1-1_amd64.deb
  - sudo dpkg -i libenet-plus-dev_0.1-1_amd64.deb

  # pugixml 1.5
  - wget https://github.com/zeux/pugixml/releases/download/v1.5/pugixml-1.5.zip
  - unzip pugixml-1.5.zip
  - cd pugixml-1.5/scripts/
  - mkdir build && cd build/
  - cmake ..
  - make
  - sudo make install
  - cd ../../../

  # libconfig
  - sudo apt-get install libconfig-dev libconfig++-dev

before_script:
  - sudo add-apt-repository ppa:codegear/release -y
  - sudo apt-get update -q
  - sudo apt-get install premake4
  - premake4 gmake

script:
  - $CXX --version
  - cd build
  - make config=debug64
